name: Build and Push the mapping mediator image

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push tag
        if: ${{ github.ref_name != 'master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: talexie/openhim-mediator-mapping:${{ github.ref_name }}

      - name: Build and push latest
        if: ${{ github.ref_name == 'master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: talexie/openhim-mediator-mapping:latest
